### ISSUE TITLE
Arredondamento de valores com NBR 5891

### ISSUE THREAD

**Issue by aledevbr** [sacfiscal/FiscalNet_old#1]
Essa issue é mais uma dúvida/sugestão, sei que nas definições do SAT é necessário utilizar o arredondamento seguindo a norma **ABNT NBR 5891/1977**, que difere da forma como o decimal.Round() funciona. 
Não sei se para o restante dos documentos fiscais funciona o arredondamento desta NBR (eis o item da dúvida).
Para o caso do SAT e se se realmente for necessário utilizar a NBR 5891 (eis a sugestão), segue a sintaxe no C# para tal:

`Math.Round(0.3450, 2, MidpointRounding.ToEven)`

O parâmetro **MidpointRounding.ToEven** é que determina a forma de cálculo equivalente à NBR 5891 (neste exemplo ele arredonda o valor 0.3450 para 2 casas decimais, resultando em 0.34).
Se testar com 0.3350, o valor será 0.34 (idêntico ao Math.Round sem o parâmetro)

**Comment by sacfiscal** [comment]
Muito obrigado pela sugestão @aledevbr , prudente demais usar este padrão para o arredondamento. Iremos atualizar e subir versão atualizada. \o/

Adicionado no commit #7d43e59 #1
